name: bump-version
author: SLAVONchick
description: bump-version
inputs: 
  version_file:
    required: true
    description: Path to a version file
  version_mask:
    required: true
    description: Version mask tells which version number to bump. Format is '*.*.*.*'
runs:
  using: composite
  steps:
    - name: Parse Version And Bump It
      id: parse-version
      shell: pwsh
      run: |
        $version = ( `
          Select-Xml -Path ${{ inputs.version_file }} -XPath '//Version' | `
          Select-Object -ExpandProperty Node).InnerText
        $versions = $version.Split('.')
        $versionMasks = "${{ inputs.version_mask }}".Split('.')
        $bumped = $false
        for ($i = 0; $i -le 3; $i++) {
          if ($bumped) {
            $versions[$i] = "0"
            continue
          }
          $v = [int]$version[$i]
          $vm = [int]$versionMasks[$i]
          if ($vm -gt 0) {
            $v = $v + $vm
            $bumped = $true
          }
          $versions[$i] = [string]$v
        }
        $newVersion = [System.String]::Join('.', $versions)
        Set-Content -Path ${{ inputs.version_file }} -Value "<Version>$newVersion</Version>"
        Add-Content -Path "$env:GITHUB_OUTPUT" -Value "old-version=$version"
        Add-Content -Path "$env:GITHUB_OUTPUT" -Value "new-version=$newVersion"
    - name: Push New Version
      shell: pwsh
      run: |
        git config --global user.name 'version bump'
        git config --global user.email 'version-bump@users.noreply.github.com'
        git add ${{ inputs.version_file }}
        git commit -m "Automatic version bump (${{ steps.parse-version.outputs.old-version }} -> ${{ steps.parse-version.outputs.new-version }})"
        git push