# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Release

on:
  workflow_call: 
    inputs:
      pre_release:
        required: true
        type: boolean
        default: true
        description: Determines if the workflow should be run in pre release mode



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: .NET Tool Restore
        run: dotnet tool restore
      - name: Set Input Parameters
        run: |
          VERSION_SUFFIX=$(if [ ${{ inputs.pre_release }} ]; then echo "rc"; else echo ""; fi)
          VERSION_MASK=$(if [ ${{ inputs.pre_release }} ]; then echo "0.0.0.1"; else echo "0.0.1.0"; fi)          
          CONFIGURATION=$(if [ ${{ inputs.pre_release }} ]; then echo "Debug"; else echo "Release"; fi)
          echo "CONFIGURATION=$CONFIGURATION"
          echo "CONFIGURATION=$CONFIGURATION" >> $GITHUB_ENV
          echo "VERSION_MASK=$VERSION_MASK"
          echo "VERSION_MASK=$VERSION_MASK" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=$VERSION_SUFFIX"
          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV
      - name: Version Bump
        uses: SiqiLu/dotnet-bump-version@2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version_mask: ${{ env.VERSION_MASK }}
          version_files: "version.xml"
      - name: Set Version Env Var
        run: |
          LIBRARY_VERSION=$(dotnet pwsh -c "(Select-Xml -Path ./version.xml -XPath '/Version' | Select-Object -ExpandProperty Node).InnerText")
          FULL_LIBRARY_VERSION="$LIBRARY_VERSION$(if ${{ inputs.pre_release }}; then echo "-${{ env.VERSION_SUFFIX }}"; else echo ""; fi)"
          LIBRARY_TAG="v$FULL_LIBRARY_VERSION"
          echo "LIBRARY_VERSION=$LIBRARY_VERSION" >> $GITHUB_ENV
          echo "FULL_LIBRARY_VERSION=$FULL_LIBRARY_VERSION" >> $GITHUB_ENV
          echo "LIBRARY_TAG=$LIBRARY_TAG" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore /p:VersionPrefix=${{ env.LIBRARY_VERSION }}  /p:VersionSuffix=${{ env.VERSION_SUFFIX }} -c ${{ env.CONFIGURATION }} 
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings ./tests/TempMail.Client.Tests/coverlet.runsettings --results-directory ./coverage -c ${{ env.CONFIGURATION }}
      - name: Code Coverage Summary
        run: |
          dotnet pwsh -c \
          '
            $lr = [System.Math]::Round( `
              $( `
                Select-Xml -Path ./coverage/*/coverage.cobertura.xml -XPath "//package" ` 
                | Select-Object -ExpandProperty Node `
                | Select-Object -Property line-rate)."line-rate", 2 `
              ) * 100;
            @{ 
              files = @{ 
                "temp-mail-dotnet-code-coverage.json" = @{
                  content = $(@{
                    schemaVersion = 1;
                    label = "Code Coverage";
                    message = $lr.ToString();
                    color = (&{if ($lr -ge 80) {"green"} else { if ($lr -ge 50) {"yellow"} else {"orange"} } })
                  } | ConvertTo-Json)
                }
              } 
            } | ConvertTo-Json' > code-coverage-badge.json
      - name: Create Awesome Badge
        run: |
          data=$(cat code-coverage-badge.json)
          echo "$data"
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_GIST_API_KEY }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/gists/89c85cdd66cced45519b7928f2740687" \
          -d "$data"
      - name: Publish NuGet Packages
        run: |
          mkdir ./package
          cp ./src/TempMail.Client/bin/Debug/TempMail.Client.*.nupkg ./package
          cp ./src/TempMail.Client.AspNetCore/bin/Debug/TempMail.Client.AspNetCore.*.nupkg ./package
          dotnet nuget push ./package/TempMail.Client.*.nupkg -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json
      - name: GitHub Tag
        uses: IIlyichev/github-tag-action@v6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.LIBRARY_TAG }}
          tag_prefix: ""
      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: "## NuGet Packages: \n* [TempMail.Client](https://www.nuget.org/packages/TempMail.Client/${{ env.FULL_LIBRARY_VERSION }}) \n* [TempMail.Client.AspNetCore](https://www.nuget.org/packages/TempMail.Client.AspNetCore/${{ env.FULL_LIBRARY_VERSION }})"
          prerelease: ${{ inputs.pre_release }}
          tag_name: ${{ env.LIBRARY_TAG }}
          name: ${{ env.LIBRARY_TAG }}
          generate_release_notes: true
          append_body: true
          files: ./package/*