name: .NET Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Version Bump
        uses: SiqiLu/dotnet-bump-version@2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version_mask: 0.0.1.0
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet pack --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish TempMail.Client NuGet Package
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: ./src/TempMail.Client/TempMail.Client.csproj
          NUGET_KEY: ${{secrets.NUGET_ORG_API_KEY}}
          INCLUDE_SYMBOLS: true
      - name: Publish TempMail.Client.AspNetCore NuGet Package
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: ./src/TempMail.Client.AspNetCore/TempMail.Client.AspNetCore.csproj
          NUGET_KEY: ${{secrets.NUGET_ORG_API_KEY}}
          INCLUDE_SYMBOLS: true