name: Build & Test

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: .NET Tool Restore
        run: dotnet tool restore
      # just pass anything to parameters, since the build output won't be released
      - name: Build & Test
        uses: ./.github/actions/build-n-test
        with:
          library_version: 0.0.0.1
          version_suffix: ""
          configuration: Debug