name: Pushed to `master`

on:
  push: 
    branches:
      - "master"
        
        
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Whole Pipeline
        uses: ./.github/dotnet-release
        with:
          pre_release: false