name: Pushed to `feature/**`

on:
  push: 
    branches:
      - "feature/**"
        
        
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Whole Pipeline
        uses: temp-mail-io/temp-mail-dotnet/.github/dotnet-release/action.yml@${{ github.sha }}
        with:
          pre_release: true