name: Pushed to `feature/**`

on:
  push: 
    branches:
      - "feature/**"
        
        
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: What's happening?
        run: ls -lah
      - name: Run Whole Pipeline
        uses: ./.github/dotnet-release.yml
        with:
          pre_release: true