name: Pushed to `master`

on:
  push: 
    branches:
      - "master"        
        
jobs: 
  release-dotnet:
    uses: ./.github/workflows/dotnet-release.yml
    with: 
      pre_release: false
    secrets: inherit
  